import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./provider/page";
import Footer from "./components/footer";
import Sidebar from "./components/sidebar";
import Header from "./components/header";

export const metadata: Metadata = {
  title: "Loop it",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-950">
        <Header />
        <div className="flex">
          <div className="">
            <Sidebar />
          </div>
          <main className="flex-1 mt-5">
            <Providers>{children}</Providers>
          </main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
