import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./provider/page";
import Footer from "./components/footer";
import Sidebar from "./components/sidebar";
import Header from "./components/header";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Loop it",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body  className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-950`} bg-zinc-950 > */}
      <body className="bg-gray-950 p-3">
        <Header />
        <div className="flex">
          <div className="">
            <Sidebar />
          </div>
          <main className="flex-1 my-3">
            {/* <section className="grid grid-cols-2 gap-5 mx-5 md:grid-cols-6 md:px-40 md:gap-10 pb-10"> */}
            <Providers>{children}</Providers>
            {/* </section> */}
          </main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
